version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - artyom
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - "> 1.28.10, < 1.29"
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - ">= 1.29.a, < 1.30"
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - "> 1.30.1, < 1.31"
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - "> 1.31.3"
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - "> 1.31.3, < 1.32"
  - dependency-name: github.com/go-sql-driver/mysql
    versions:
    - 1.6.0
